version: 2.1
jobs:
  deploy_site:
    docker:
      - image: jschaf/blog-builder
    steps:
      - checkout
      - run:
          name: Deploying the site
          command: make deploy

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy_site
