version: 2.1
jobs:
  deploy_site:
    docker:
      - image: jschaf/blog-builder
    steps:
      - checkout
      - run:
          name: Deploying the site
          command: make deploy
  build_docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Building blog-builder image
          command: make push-docker-image

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy_site
      - build_docker
