version: 2.1
jobs:
  # Checks out the code and persists it to a CircleCI workspace.
  checkout_code:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Creating Docker cache key
          command: .circleci/create_docker_cache_key.sh
      - persist_to_workspace:
          root: .
          paths: [.]

  build_docker:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restoring Docker precheck build cache
          keys: ['docker-precheck-cache-{{ checksum ".circleci/docker_cache_key" }}']
      - run:
          name: Skipping job if the currently pushed Docker image is fresh
          command: .circleci/check_docker_staleness.sh
      - restore_cache:
          name: Restoring Docker image cache
          keys: ["docker-layer-cache-v1-"]
      - run:
          name: Building Docker image
          command: |
            if [[ -f /dev/shm/blog-builder.tar.gz ]]; then
              docker load --input /dev/shm/blog-builder.tar.gz
            fi
            make docker-image
      - run:
          name: Saving Docker image as compressed tar file
          command: |
            docker save jschaf/blog-builder:latest |
                gzip > /dev/shm/blog-builder.tar.gz
            # Copy precheck cache file to correct spot
            cp .circleci/docker_cache_key .circleci/docker_precheck_cache_key
      - run:
          name: Pushing Docker image
          command: |
            echo "${DOCKER_HUB_TOKEN}" |
                docker login --username jschaf --password-stdin
            make push-docker-image
      - save_cache:
          name: Saving cache for node_modules precheck key
          key: docker-precheck-cache-{{ checksum ".circleci/docker_cache_key" }}
          paths: [".circleci/docker_precheck_cache_key"]
      - save_cache:
          name: Saving cache for Docker image
          key: docker-layer-cache-v1-{{ epoch }}
          paths: ["/dev/shm/blog-builder.tar.gz"]

  deploy_site:
    docker:
      - image: jschaf/blog-builder:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploying the site
          command: make deploy

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - checkout_code
      - build_docker:
          requires: [checkout_code]
      - deploy_site:
          requires: [checkout_code, build_docker]
