---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - FIREBASE_TOKEN=1/4aTSMmJo7K0ScDhRKyAaeSIf_dZT-X7jh9tagHSddok
  preview_output_directory: dist
  preview_docker_image: jschaf/blog-builder
  mount_path: "/home/blog-builder/b2"
  working_dir: "/home/blog-builder/b2"
  instant_preview_command: make dev
