name: blog
on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: gcp auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.BLOG_RELEASER_SERVICE_ACCOUNT_CREDS }}'

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: html
        run: make html

      - name: publish
        run: make publish
